/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppProvider: typeof import('./src/components/AppProvider/index.vue')['default']
    BasicButton: typeof import('./src/components/BasicButton/index.vue')['default']
    Iconify: typeof import('./src/components/Iconify/index.vue')['default']
  }
}
