/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * BearPlatform Api 后端接口文档 移动端/微信小程序/钉钉/H5 - version 2.0
 *
 *
 *
 * OpenAPI version: 3.0.1
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'I18n.post_add': ['POST', '/api/I18n/Add'],
  'I18n.delete_delete': ['DELETE', '/api/I18n/Delete'],
  'I18n.get_getpage': ['GET', '/api/I18n/GetPage'],
  'I18n.put_update': ['PUT', '/api/I18n/Update'],
  'Login.get_captcha': ['GET', '/api/Login/Captcha'],
  'Login.get_getinfo': ['GET', '/api/Login/GetInfo'],
  'Login.post_login': ['POST', '/api/Login/Login'],
  'Login.post_refreshtoken': ['POST', '/api/Login/RefreshToken']
};
