/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * BearPlatform Api 后端接口文档 Web端网站 - version 1.0
 *
 *
 *
 * OpenAPI version: 3.0.1
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'Apis.post_add': ['POST', '/api/Apis/Add'],
  'Apis.delete_delete': ['DELETE', '/api/Apis/Delete'],
  'Apis.get_getpage': ['GET', '/api/Apis/GetPage'],
  'Apis.get_refresh': ['GET', '/api/Apis/Refresh'],
  'Apis.get_treeselect': ['GET', '/api/Apis/TreeSelect'],
  'Apis.put_update': ['PUT', '/api/Apis/Update'],
  'Dept.post_add': ['POST', '/api/Dept/Add'],
  'Dept.delete_delete': ['DELETE', '/api/Dept/Delete'],
  'Dept.get_getinfo': ['GET', '/api/Dept/GetInfo'],
  'Dept.get_getpage': ['GET', '/api/Dept/GetPage'],
  'Dept.put_update': ['PUT', '/api/Dept/Update'],
  'I18n.post_add': ['POST', '/api/I18n/Add'],
  'I18n.delete_delete': ['DELETE', '/api/I18n/Delete'],
  'I18n.get_getbylocale': ['GET', '/api/I18n/GetByLocale'],
  'I18n.get_getpage': ['GET', '/api/I18n/GetPage'],
  'I18n.put_update': ['PUT', '/api/I18n/Update'],
  'Job.post_add': ['POST', '/api/Job/Add'],
  'Job.delete_delete': ['DELETE', '/api/Job/Delete'],
  'Job.get_getinfo': ['GET', '/api/Job/GetInfo'],
  'Job.get_getpage': ['GET', '/api/Job/GetPage'],
  'Job.put_update': ['PUT', '/api/Job/Update'],
  'Login.get_captcha': ['GET', '/api/Login/Captcha'],
  'Login.get_getinfo': ['GET', '/api/Login/GetInfo'],
  'Login.post_login': ['POST', '/api/Login/Login'],
  'Login.post_refreshtoken': ['POST', '/api/Login/RefreshToken'],
  'Menu.post_add': ['POST', '/api/Menu/Add'],
  'Menu.get_constantroutes': ['GET', '/api/Menu/ConstantRoutes'],
  'Menu.delete_delete': ['DELETE', '/api/Menu/Delete'],
  'Menu.get_getinfo': ['GET', '/api/Menu/GetInfo'],
  'Menu.get_gettree': ['GET', '/api/Menu/GetTree'],
  'Menu.get_isrouteexist': ['GET', '/api/Menu/IsRouteExist'],
  'Menu.get_myroutes': ['GET', '/api/Menu/MyRoutes'],
  'Menu.get_treeselect': ['GET', '/api/Menu/TreeSelect'],
  'Menu.put_update': ['PUT', '/api/Menu/Update'],
  'Role.post_add': ['POST', '/api/Role/Add'],
  'Role.delete_delete': ['DELETE', '/api/Role/Delete'],
  'Role.get_getpage': ['GET', '/api/Role/GetPage'],
  'Role.get_getpermission': ['GET', '/api/Role/GetPermission'],
  'Role.post_setpermission': ['POST', '/api/Role/SetPermission'],
  'Role.put_update': ['PUT', '/api/Role/Update'],
  'TableDynamic.get_configid_tableof': ['GET', '/api/TableDynamic/{configId}/{tableof}'],
  'TableDynamic.post_configid_tableof': ['POST', '/api/TableDynamic/{configId}/{tableof}'],
  'TableDynamic.put_configid_tableof': ['PUT', '/api/TableDynamic/{configId}/{tableof}'],
  'TableDynamic.delete_configid_tableof': ['DELETE', '/api/TableDynamic/{configId}/{tableof}'],
  'TableForm.post_add': ['POST', '/api/TableForm/Add'],
  'TableForm.get_getform': ['GET', '/api/TableForm/GetForm'],
  'TableForm.get_gettableform': ['GET', '/api/TableForm/GetTableForm'],
  'TableForm.put_update': ['PUT', '/api/TableForm/Update'],
  'TableFormItem.delete_delete': ['DELETE', '/api/TableFormItem/Delete'],
  'TableFormItem.put_setattrs': ['PUT', '/api/TableFormItem/SetAttrs'],
  'TableFormItem.put_setformitem': ['PUT', '/api/TableFormItem/SetFormItem'],
  'TableFormItem.put_setsort': ['PUT', '/api/TableFormItem/SetSort'],
  'TableView.get_getedit': ['GET', '/api/TableView/GetEdit'],
  'TableView.get_getview': ['GET', '/api/TableView/GetView'],
  'TableView.post_setedit': ['POST', '/api/TableView/SetEdit'],
  'Tenant.post_add': ['POST', '/api/Tenant/Add'],
  'Tenant.delete_delete': ['DELETE', '/api/Tenant/Delete'],
  'Tenant.get_getinfo': ['GET', '/api/Tenant/GetInfo'],
  'Tenant.get_getpage': ['GET', '/api/Tenant/GetPage'],
  'Tenant.put_update': ['PUT', '/api/Tenant/Update']
};
